[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://chat-backend-haeb.onrender.com"
  VITE_API_BASE_URL = "https://chat-backend-haeb.onrender.com"
